#pragma once
//#define TRADITIONALSKELETALANIMATION //remove to have OBB skeletal animation else traditional skeletal animation is running
//#define ONEBONE
#define ORGINALPOSITION


//OPTIONS
// TRADITIONALSKELETALANIMATION = FALSE
// ONEBONE = FALSE
// ORGINALPOSITION = FALSE

// TRADITIONALSKELETALANIMATION = TRUE
// ONEBONE = FALSE
// ORGINALPOSITION = FALSE

// TRADITIONALSKELETALANIMATION = TRUE
// ONEBONE = TRUE
// ORGINALPOSITION = FALSE

// TRADITIONALSKELETALANIMATION = FALSE
// ONEBONE = FALSE
// ORGINALPOSITION = TRUE


